[GROQ]
API_KEY = ""
API_URL = "https://api.groq.com/openai/v1/chat/completions"
MODEL = "openai/gpt-oss-20b"

[HUGGINGFACE]
API_KEY = ""
API_URL = "https://router.huggingface.co/v1"
MODEL = "meta-llama/Llama-3.1-8B-Instruct"

Convert the file name to secret.toml and remvoe this line